FROM ruby:2.4.0
MAINTAINER data@localytics.com

ENV    DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y install libnss3-tools unixodbc-dev libmyodbc mysql-client odbc-postgresql  postgresql

WORKDIR /workspace
CMD docker/docker-entrypoint.sh